name: Update README from Template

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to update in the target repository'
        required: true
        default: 'main'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.target_branch }}

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Clone template repository
      run: |
        git clone https://github.com/dockersamples/sample-app-template.git template-repo
        cp template-repo/README.md .

    - name: Commit and push changes
      run: |
        git add README.md
        git commit -m "Update README.md from template repository" || echo "No changes to commit"
        git push origin ${{ github.event.inputs.target_branch }}

    - name: Clean up
      run: rm -rf template-repo
